### ISSUE TITLE
FusionException doesn't exist 

### ISSUE THREAD

**Issue by Sebobo** [neos/fusion-afx#22]
https://github.com/neos/fusion-afx/blob/b7574d371128251000d4e7499d9910f05558bb01/Classes/Dsl/AfxDslImplementation.php#L30

When afx throws an error there is another exception as the `FusionException` does not exist. 
Which Exception type should be thrown here?

**Comment by mficzel** [comment]
This one here https://github.com/neos/neos-development-collection/blob/master/Neos.Fusion/Classes/Exception.php as the FusionDslInterface says.

**Comment by mficzel** [comment]
Maybe a use statement is missing
