### ISSUE TITLE
Properties with @

### ISSUE THREAD

**Issue by jonnitto** [neos/fusion-afx#34]
If you want to use libraries like [Alpine.js](https://github.com/alpinejs/alpine), it is not possible to add properties with `@`. In pure Fusion it works:

```
tag = Neos.Fusion:Tag {
  attributes {
     '@click' = 'Test'
  }
  content = 'Text'
}
```

This doesn't work:
```
renderer = afx`
  <div '@click'='Test'>Text</div>
`
```

**Comment by jonnitto** [comment]
Another option would be if specific `@` annotations could be configured in `Settings.yaml`, so it could work without `'`: 
`<div @click='Test'>Text</div>`

**Comment by kitsunet** [comment]
I would harshly argue that attributes starting with @ are not HTML conforming and therefore we shouldn't support them and the bad practice of using them.

**Comment by jonnitto** [comment]
I understand you, @kitsunet but: In pure Fusion it works, so I would expect that `<div '@click'='Test'>Text</div>` would work. Besides Alpine.js Vue.js also use this pattern.

**Comment by mficzel** [comment]
I doubt that we will find a way to do this. Only possible solution i see would be to make the meta-character configurable for each afx call so you can use any character you like for that like `afx('$')`<div @click='Test'` $if.enables={props.enabled} />`

Do not really like this and the change would be quite big. Allthough this would affect the dsl implememtation on the fusion side aswell.

**Comment by jonnitto** [comment]
As the `@` this is a shortcut for `x:on` I can write it the other way…
But this one is really annoying: https://github.com/neos/neos-development-collection/issues/3112
